# Generated by Django 5.1.3 on 2025-07-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewear', '0003_remove_customuser_posts_post_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gallary',
        ),
        migrations.AddField(
            model_name='customuser',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
