# Generated by Django 5.1.3 on 2025-07-12 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewear', '0005_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('post1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_post1', to='rewear.post')),
                ('post2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_post2', to='rewear.post')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
